use_frameworks!

target 'JXFoundation_Example' do
  pod 'JXFoundation', :path => '../'

  target 'JXFoundation_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots' 
  end
end
